version: '2'
services:
    financas-mysql:
        image: mysql:5.7.26
        restart: always
        container_name: financas-mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
    financas-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: instalura-phpmyadmin
        ports:
            - "8085:80"
        environment:
            - PMA_HOST=financas-mysql
        links:
            - financas-mysql
        depends_on:
          - financas-mysql
